version: '2'
services:
    jhipsteronlinefoodmanager-app:
        image: jhipsteronlinefoodmanager
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipsteronlinefoodmanager-postgresql:5432/jhipsterOnlineFoodManager
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipsteronlinefoodmanager-postgresql:
        extends:
            file: postgresql.yml
            service: jhipsteronlinefoodmanager-postgresql
